INSERT INTO breeds (id, breed_name) VALUES
    (1, 'Labrador Retriever'),
    (2, 'German Shepherd'),
    (3, 'Golden Retriever'),
    (4, 'Bulldog'),
    (5, 'Beagle'),
    (6, 'French Bulldog'),
    (7, 'Poodle'),
    (8, 'Rottweiler'),
    (9, 'Yorkshire Terrier'),
    (10, 'Boxer'),
    (11, 'Siberian Husky'),
    (12, 'Dachshund'),
    (13, 'Doberman Pinscher'),
    (14, 'Chihuahua'),
    (15, 'Shih Tzu'),
    (16, 'Australian Shepherd'),
    (17, 'Great Dane'),
    (18, 'Cavalier King Charles Spaniel'),
    (19, 'Shetland Sheepdog'),
    (20, 'Boston Terrier'),
    (21, 'Pembroke Welsh Corgi'),
    (22, 'Bernese Mountain Dog'),
    (23, 'Miniature Schnauzer'),
    (24, 'English Springer Spaniel'),
    (25, 'Brittany'),
    (26, 'Basset Hound'),
    (27, 'Weimaraner'),
    (28, 'Border Collie'),
    (29, 'Newfoundland'),
    (30, 'West Highland White Terrier'),
    (31, 'Staffordshire Bull Terrier'),
    (32, 'Maltese'),
    (33, 'Cocker Spaniel'),
    (34, 'Shiba Inu'),
    (35, 'Saint Bernard'),
    (36, 'Bichon Frise'),
    (37, 'Bloodhound'),
    (38, 'Mastiff'),
    (39, 'Akita'),
    (40, 'Old English Sheepdog'),
    (41, 'Schnauzer'),
    (42, 'Collie'),
    (43, 'Siberian Husky'),
    (44, 'American Pit Bull Terrier'),
    (45, 'Dalmatian'),
    (46, 'Vizsla'),
    (47, 'German Shorthaired Pointer'),
    (48, 'Irish Setter'),
    (49, 'English Cocker Spaniel'),
    (50, 'Rhodesian Ridgeback');
