#spring:
#  mvc:
#    cors:
#      allowed-origins: "*"
#      allowed-methods: "GET, POST, PUT, DELETE"
#      allowed-headers: "*"
#

spring.webflux.cors:
  cors:
    allowed-origins: "http://localhost:63342"
    allowed-methods: GET, POST, PUT, DELETE
    allowed-headers: "*"
